########################
#   Database Settings
########################
spring:
  datasource:
    url: jdbc:postgresql://in.the.cloud:5432/gandalf
    platform: postgres
    name: gandalf
    username: gandalf
    password: superhemmelig
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation=true:


